name: Unearth Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image: node:10.16-jessie

    services:
      postgres:
        image: postgres:9.6
        env:
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DB: unearth-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.x'
      - run: yarn install
      - run: yarn test
        env:
          CI: true
          NODE_ENV: test
          # use postgres for the host here because we have specified a container for the job.
          # If we were running the job on the VM this would be localhost
          PG_HOST: postgres
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_PORT: ${{ job.services.postgres.ports[5432] }}
          PG_DB: unearth-test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/unearth-test
