name: Unearth Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  containerized-tests:
    runs-on: ubuntu-latest
    container: node:10.16-jessie

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: unearth-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.x'
      - run: yarn install
      - run: yarn test
        env:
          CI: true
          NODE_ENV: test
          DB_HOST: postgres
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: unearth-test
